name: Auto Approve Check

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get changed files that aren't pre-approved
        id: changed-files
        uses: tj-actions/changed-files@v36
        with:
          # The following is a list of blobs that will be automatically approved.
          files_ignore: |
            approved/**

      - name: Approve PR
        id: approve
        if: steps.changed-files.outputs.all_changed_and_modified_files == ''
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Dismiss review
        uses: actions/github-script@v6
        if: steps.changed-files.outputs.all_changed_and_modified_files != ''
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const botName = "github-actions[bot]";
            const reviews = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const botReview = reviews.data.find(review => review.user.login === botName);

            if(botReview) {
              await github.pulls.dismissReview({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                review_id: botReview.id,
                message: 'Dismissing bot review'
              });
            }
