name: Auto Approve Check

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      # - name: Checkout PR
      #   uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0
      #     ref: ${{ github.event.pull_request.head.ref }}

      # - name: Install Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'

      # - name: Install dependencies
      #   run: npm install

      # - name: Get changed files that aren't pre-approved
      #   id: changed-files
      #   uses: tj-actions/changed-files@v36
      #   with:
      #     # The following is a list of blobs that will be automatically approved.
      #     files_ignore: |
      #       approved/**

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Approve PR
        id: approve
        if: steps.changed-files.outputs.all_changed_and_modified_files == ''
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
    
      # - name: Display changed files
      #   run: echo "${{ steps.changed-files.outputs.all_changed_and_modified_files }}"
